% © 2020–2025 Deniz Varılsüha — Non-commercial research use only. See LICENSE.
% Contact: deniz.varilsuha@itu.edu.tr
function [base] = basemergeMexSF(base,set)

base.T1r=[];base.T1c=[];base.T1v=[];
base.T2r=[];base.T2c=[];base.T2v=[];
base.T3r=[];base.T3c=[];base.T3v=[];
base.Q2r=[];base.Q2c=[];base.Q2v=[];

[base.T1r,base.T1c,base.T1v,base.T2r,base.T2c,base.T2v,base.T3r,base.T3c,base.T3v,base.Q2r,base.Q2c,base.Q2v]=...
baseMergeHYBCF(base.WMr,base.WMc,base.WMv,base.m,base.AK1r,base.AK1c,base.AK1v,base.AK2r,base.AK2c,base.AK2v,base.AK3r,base.AK3c,base.AK3v,...
base.AM1r,base.AM1c,base.AM1v,base.AM2r,base.AM2c,base.AM2v,base.AM3r,base.AM3c,base.AM3v,base.AM4r,base.AM4c,base.AM4v, ...
base.AD1r,base.AD1c,base.AD1v,base.AD2r,base.AD2c,base.AD2v,base.AD3r,base.AD3c,base.AD3v,base.AD4r,base.AD4c,base.AD4v,...
base.AD5r,base.AD5c,base.AD5v,base.AD6r,base.AD6c,base.AD6v,base.AD7r,base.AD7c,base.AD7v,base.AD8r,base.AD8c,base.AD8v,...
base.AL1r,base.AL1c,base.AL1v,base.AL2r,base.AL2c,base.AL2v,base.AL3r,base.AL3c,base.AL3v,base.AL4r,base.AL4c,base.AL4v,...
base.AL5r,base.AL5c,base.AL5v,base.AL6r,base.AL6c,base.AL6v,base.AL7r,base.AL7c,base.AL7v,base.AL8r,base.AL8c,base.AL8v,...
base.BK1r,base.BK1c,base.BK1v,base.BK2r,base.BK2c,base.BK2v,base.BK3r,base.BK3c,base.BK3v,...
base.BM1r,base.BM1c,base.BM1v,base.BM2r,base.BM2c,base.BM2v,base.BM3r,base.BM3c,base.BM3v,base.BM4r,base.BM4c,base.BM4v,...
base.BD1r,base.BD1c,base.BD1v,base.BD2r,base.BD2c,base.BD2v,base.BD3r,base.BD3c,base.BD3v,base.BD4r,base.BD4c,base.BD4v,...
base.BD5r,base.BD5c,base.BD5v,base.BD6r,base.BD6c,base.BD6v, base.BD7r,base.BD7c,base.BD7v,base.BD8r,base.BD8c,base.BD8v,...
base.BL1r,base.BL1c,base.BL1v,base.BL2r,base.BL2c,base.BL2v,base.BL3r,base.BL3c,base.BL3v,base.BL4r,base.BL4c,base.BL4v,...
base.BL5r,base.BL5c,base.BL5v,base.BL6r,base.BL6c,base.BL6v,base.BL7r,base.BL7c,base.BL7v,base.BL8r,base.BL8c,base.BL8v,...
base.W1r,base.W1c,base.W1v,base.W2r,base.W2c,base.W2v,base.W3r,base.W3c,base.W3v,base.W4r,base.W4c,base.W4v,...
base.W5r,base.W5c,base.W5v,base.W6r,base.W6c,base.W6v,base.W7r,base.W7c,base.W7v,base.W8r,base.W8c,base.W8v,...
base.AK0r,base.AK0c,base.AK0v,base.BK0r,base.BK0c,base.BK0v);

end
